// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/minnowo/astoryofand/view"
	"github.com/minnowo/astoryofand/view/layout"
)

func ShowAboutPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := `

            main {
                background: rgba(255,255,255,0.5);
            }

            .special_form {
                height: 100%;
            }

            .title {
                max-width: 100%;
                height: auto;
            }

            .image1, .image2, .image3 {
                display: inline-block;
                height:fit-content!important;
                max-width: none !important;
                max-height: none !important;
            }

            .image1 {
                width: 15%  !important;
            }

            .image2 {
                width: 55%  !important;
            }

            .image3 {
                width: 50px  !important;
                margin-left: 0;
            }

            .image4 {
                width: 80%  !important;
            }

            .quote_container {
                display: flex;
            }

            .bubble_bg {
                background: url(/static/images/bubble.png);
                background-size: 100% 100%;
                background-repeat: no-repeat;
            }


        `
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style> <form class=\"special_form\"><div class=\"quote_container\"><img class=\"title nobg noborder\" src=\"/static/images/title.png\" style=\"margin-bottom: -50px;\"></div><div class=\"quote_container bubble_bg\"><img class=\"image4 title nobg noborder\" src=\"/static/images/text1.png\" style=\"padding-top: 100px; padding-bottom: 100px;\"></div><div class=\"quote_container\"><img class=\"image3 flipim nobg noborder\" src=\"/static/images/megaphone_man.png\"><div style=\"max-width: 850px;\"><img class=\"image1 nobg noborder\" src=\"/static/images/mich.png\"> <img class=\"image2 nobg noborder\" src=\"/static/images/text.png\"> <img class=\"image1 nobg noborder\" src=\"/static/images/jo.png\" style=\"margin-top: 10%;\"></div></div><div class=\"quote_container\"></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Page2(view.PAGE_TITLE).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
